# Generated by Django 3.1 on 2023-02-16 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20230214_2157'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='variation',
            managers=[
            ],
        ),
    ]
